/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package my.company.javagui;

/**
 *
 * @author Gian Vilcan Patra
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;

public class PBOTeoriGUI extends javax.swing.JFrame {

    /**
     *
     */
    public PBOTeoriGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        TeksNama = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        TeksAlamat = new javax.swing.JTextField();
        TeksTelp = new javax.swing.JTextField();
        LabelAlamat = new javax.swing.JLabel();
        LabelTelepon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dataCustomer = new javax.swing.JLabel();
        pilihMenu = new javax.swing.JLabel();
        menuSpa = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        menuSteak = new javax.swing.JCheckBox();
        menuPizza = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labelTotalBayar = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        labelDataPenjualan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dataPenjualan = new javax.swing.JTextArea();
        simpanTeks = new javax.swing.JButton();
        loadTeks = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pemesanan Makanan");

        TeksNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksNamaActionPerformed(evt);
            }
        });

        LabelNama.setText("Nama :");

        TeksAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksAlamatActionPerformed(evt);
            }
        });

        LabelAlamat.setText("Alamat :");

        LabelTelepon.setText("No. Telp :");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Pemesanan");

        dataCustomer.setText("Data Customer");

        pilihMenu.setText("Pilih Menu");

        menuSpa.setText("Spaghetti");
        menuSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSpaActionPerformed(evt);
            }
        });

        menuSteak.setText("Steak");
        menuSteak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSteakActionPerformed(evt);
            }
        });

        menuPizza.setText("Pizza");
        menuPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPizzaActionPerformed(evt);
            }
        });

        labelTotalBayar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        labelTotalBayar.setText("Total Bayar");

        totalBayar.setEditable(false);
        totalBayar.setBackground(new java.awt.Color(0, 0, 0));
        totalBayar.setForeground(new java.awt.Color(255, 255, 0));
        totalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBayarActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        labelDataPenjualan.setText("Data Penjualan");

        dataPenjualan.setEditable(false);
        dataPenjualan.setColumns(20);
        dataPenjualan.setRows(5);
        jScrollPane3.setViewportView(dataPenjualan);

        simpanTeks.setText("Simpan Teks");
        simpanTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTeksActionPerformed(evt);
            }
        });

        loadTeks.setText("Load Teks");
        loadTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTeksActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalBayar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Tambah)
                                .addGap(10, 10, 10)))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelTelepon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNama, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TeksTelp)
                                    .addComponent(TeksAlamat)
                                    .addComponent(TeksNama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dataCustomer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1))))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuSpa)
                            .addComponent(menuSteak)
                            .addComponent(menuPizza)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pilihMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelDataPenjualan)
                .addGap(0, 513, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(simpanTeks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(129, 129, 129)
                .addComponent(loadTeks)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pilihMenu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuSpa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuSteak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(dataCustomer)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNama)
                            .addComponent(TeksNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAlamat)
                            .addComponent(TeksAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeksTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTelepon))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tambah)
                .addGap(9, 9, 9)
                .addComponent(labelDataPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanTeks)
                    .addComponent(clear)
                    .addComponent(loadTeks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void initialForm(){
        TeksNama.setText("");
        TeksAlamat.setText("");
        TeksTelp.setText("");
        menuSpa.setSelected(false);
        menuSteak.setSelected(false);
        menuPizza.setSelected(false);
    }
    private void getTotalBayar(){
        int totBayar=0;
        if(menuSpa.isSelected()){
            totBayar += 40000;
        }
        if(menuSteak.isSelected()){
            totBayar += 50000;
        }
        if(menuPizza.isSelected()){
            totBayar += 80000;
        }
        totalBayar.setText(String.valueOf(totBayar));
    }
    private void TeksNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksNamaActionPerformed

    private void menuSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSpaActionPerformed
        // TODO add your handling code here:
        getTotalBayar();
    }//GEN-LAST:event_menuSpaActionPerformed

    private void menuPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPizzaActionPerformed
        // TODO add your handling code here:
        getTotalBayar();
    }//GEN-LAST:event_menuPizzaActionPerformed

    private void TeksAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksAlamatActionPerformed

    private void totalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBayarActionPerformed

    private void menuSteakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSteakActionPerformed
        // TODO add your handling code here:
        getTotalBayar();
    }//GEN-LAST:event_menuSteakActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        dataPenjualan.setText("Nama : " +TeksNama.getText() +"\n");
        dataPenjualan.setText(dataPenjualan.getText()+"Alamat : " +TeksAlamat.getText() +"\n");
        dataPenjualan.setText(dataPenjualan.getText()+"No Telp : " +TeksTelp.getText() + "\n");
        dataPenjualan.setText(dataPenjualan.getText()+"--------------------------------------\n");
        dataPenjualan.setText(dataPenjualan.getText()+"Pesanan : \n");
        if(menuSpa.isSelected()){
            dataPenjualan.setText(dataPenjualan.getText()+"- Spaghetti(40000)\n");
        }
        if(menuSteak.isSelected()){
            dataPenjualan.setText(dataPenjualan.getText()+"- Steak(50000)\n");
        }
        if(menuPizza.isSelected()){
            dataPenjualan.setText(dataPenjualan.getText()+"- Pizza(80000)\n");
        }
        dataPenjualan.setText(dataPenjualan.getText()+"--------------------------------------\n");
        dataPenjualan.setText(dataPenjualan.getText()+"Total Bayar : \n");
        dataPenjualan.setText(dataPenjualan.getText()+"Rp. " +totalBayar.getText());
    }//GEN-LAST:event_TambahActionPerformed

    private void loadTeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTeksActionPerformed
        // TODO add your handling code here:
        try{
            File filePesanan = new File("C:\\Users\\Gian Vilcan Patra\\OneDrive\\Documents\\NetBeansProjects\\12javagui\\src\\main\\java\\my\\company\\javagui\\pesanan.txt");
            FileReader fr = new FileReader(filePesanan);
            BufferedReader rd = new BufferedReader(fr);
            
            dataPenjualan.setText("");
            String line = null;
            while((line = rd.readLine()) != null){
                dataPenjualan.setText(dataPenjualan.getText()+line+"\n");
            }
            rd.close();
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loadTeksActionPerformed

    private void simpanTeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTeksActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter("C:\\Users\\Gian Vilcan Patra\\OneDrive\\Documents\\NetBeansProjects\\12javagui\\src\\main\\java\\my\\company\\javagui\\pesanan.txt");
            fw.write(dataPenjualan.getText());
            fw.close();
        } catch(IOException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_simpanTeksActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        dataPenjualan.setText("");
    }//GEN-LAST:event_clearActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBOTeoriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBOTeoriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBOTeoriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBOTeoriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PBOTeoriGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTelepon;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField TeksAlamat;
    private javax.swing.JTextField TeksNama;
    private javax.swing.JTextField TeksTelp;
    private javax.swing.JButton clear;
    private javax.swing.JLabel dataCustomer;
    private javax.swing.JTextArea dataPenjualan;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelDataPenjualan;
    private javax.swing.JLabel labelTotalBayar;
    private javax.swing.JButton loadTeks;
    private javax.swing.JCheckBox menuPizza;
    private javax.swing.JCheckBox menuSpa;
    private javax.swing.JCheckBox menuSteak;
    private javax.swing.JLabel pilihMenu;
    private javax.swing.JButton simpanTeks;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}

